name: Delete CloudFormation Stack

on:
  workflow_dispatch:
    inputs:
      confirm_delete:
        description: 'Type YES to confirm stack deletion'
        required: true

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Check confirmation
        run: |
          if [ "${{ github.event.inputs.confirm_delete }}" != "YES" ]; then
            echo "❌ Delete confirmation not provided. Exiting."
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Delete CloudFormation Stack
        run: |
          aws cloudformation delete-stack             --stack-name MyS3BucketStack

          echo "Waiting for stack deletion to complete..."
          aws cloudformation wait stack-delete-complete             --stack-name MyS3BucketStack

          echo "✅ Stack deleted successfully."
